In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("kidney_disease.csv")

In [3]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [4]:
dataset.isnull().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

# particular column-------->missing percentage identify

In [5]:
missing_age = dataset['age'].isnull().sum()  # Count missing values in the 'age' column
missing_percentage = (missing_age / len(dataset)) * 100  # Calculate percentage of missing values
print(f"Missing values in 'age': {missing_age}")
print(f"Missing percentage in 'age': {missing_percentage:.2f}%")

Missing values in 'age': 9
Missing percentage in 'age': 2.25%

In [6]:
missing_su = dataset['su'].isnull().sum()  
missing_percentage = (missing_su / len(dataset)) * 100 
print(f"Missing values in 'age': {missing_su}")
print(f"Missing percentage in 'age': {missing_percentage:.2f}%")

Missing values in 'age': 49
Missing percentage in 'age': 12.25%

In [7]:
missing_rbc = dataset['rbc'].isnull().sum()  
missing_percentage = (missing_rbc / len(dataset)) * 100 
print(f"Missing values in 'age': {missing_rbc}")
print(f"Missing percentage in 'age': {missing_percentage:.2f}%")

Missing values in 'age': 152
Missing percentage in 'age': 38.00%

In [8]:
missing_rc = dataset['rc'].isnull().sum()  
missing_percentage = (missing_rc / len(dataset)) * 100 
print(f"Missing values in 'age': {missing_rc}")
print(f"Missing percentage in 'age': {missing_percentage:.2f}%")

Missing values in 'age': 130
Missing percentage in 'age': 32.50%

In [9]:
missing_pot = dataset['pot'].isnull().sum()  
missing_percentage = (missing_pot / len(dataset)) * 100 
print(f"Missing values in 'age': {missing_pot}")
print(f"Missing percentage in 'age': {missing_percentage:.2f}%")

Missing values in 'age': 88
Missing percentage in 'age': 22.00%

In [10]:
missing_wc = dataset['wc'].isnull().sum()  
missing_percentage = (missing_wc / len(dataset)) * 100 
print(f"Missing values in 'age': {missing_wc}")
print(f"Missing percentage in 'age': {missing_percentage:.2f}%")

Missing values in 'age': 105
Missing percentage in 'age': 26.25%

In [11]:
missing_pcv = dataset['pcv'].isnull().sum()  
missing_percentage = (missing_pcv / len(dataset)) * 100 
print(f"Missing values in 'age': {missing_pcv}")
print(f"Missing percentage in 'age': {missing_percentage:.2f}%")

Missing values in 'age': 70
Missing percentage in 'age': 17.50%

# numerical column------>take mean

In [12]:
import pandas as pd
dataset = pd.read_csv('kidney_disease.csv')
print(dataset.head())
print(dataset.dtypes)
numerical_columns = dataset.select_dtypes(include=['float64', 'int64']).columns
mean_values = dataset[numerical_columns].mean()
#Print the mean values for each numerical column
print("\nMean values for numerical columns:")
print(mean_values)

   id   age    bp     sg   al   su     rbc        pc         pcc          ba  \
0   0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent  notpresent
1   1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent  notpresent
2   2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  notpresent
3   3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  notpresent
4   4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  notpresent

   ...  pcv    wc   rc  htn   dm  cad appet   pe  ane classification
0  ...   44  7800  5.2  yes  yes   no  good   no   no            ckd
1  ...   38  6000  NaN   no   no   no  good   no   no            ckd
2  ...   31  7500  NaN   no  yes   no  poor   no  yes            ckd
3  ...   32  6700  3.9  yes   no   no  poor  yes  yes            ckd
4  ...   35  7300  4.6   no   no   no  good   no   no            ckd

[5 rows x 26 columns]
id                  int64
age               float64
bp                float64
sg                float64
al                float64
su                float64
rbc                object
pc                 object
pcc                object
ba                 object
bgr               float64
bu                float64
sc                float64
sod               float64
pot               float64
hemo              float64
pcv                object
wc                 object
rc                 object
htn                object
dm                 object
cad                object
appet              object
pe                 object
ane                object
classification     object
dtype: object

Mean values for numerical columns:
id      199.500000
age      51.483376
bp       76.469072
sg        1.017408
al        1.016949
su        0.450142
bgr     148.036517
bu       57.425722
sc        3.072454
sod     137.528754
pot       4.627244
hemo     12.526437
dtype: float64

In [13]:
#Fill missing values in numerical columns with the mean
dataset[numerical_columns] = dataset[numerical_columns].fillna(dataset[numerical_columns].mean())

#Check again for missing values
missing_values_numerical_after_fill = dataset[numerical_columns].isnull().sum()

print("\nMissing values after filling with mean:")
print(missing_values_numerical_after_fill)

Missing values after filling with mean:
id      0
age     0
bp      0
sg      0
al      0
su      0
bgr     0
bu      0
sc      0
sod     0
pot     0
hemo    0
dtype: int64

# here we drop the missing values------>'pcv','rc','wc'

In [21]:
dataset.dropna(axis=1)

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,sod,pot,hemo,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,normal,normal,notpresent,notpresent,...,137.528754,4.627244,15.4,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,normal,normal,notpresent,notpresent,...,137.528754,4.627244,11.3,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,137.528754,4.627244,9.6,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,111.000000,2.500000,11.2,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,137.528754,4.627244,11.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,150.000000,4.900000,15.7,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,141.000000,3.500000,16.5,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,137.000000,4.400000,15.8,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,135.000000,4.900000,14.2,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,141.000000,3.500000,15.8,no,no,no,good,no,no,notckd

# categorical column--------->take--->Mode

In [22]:
categorical_columns = ['rbc','pc','pcc','ba','htn','dm','cad','appet','pe','ane']  # Add other categorical columns here
#Fill missing values in all categorical columns with the mode
for col in categorical_columns:
    dataset[col] = dataset[col].fillna(dataset[col].mode()[0])
#Check the result
print("\nUpdated DataFrame with missing values filled:")
print(dataset)

Updated DataFrame with missing values filled:
      id   age    bp     sg   al   su     rbc        pc         pcc  \
0      0  48.0  80.0  1.020  1.0  0.0  normal    normal  notpresent
1      1   7.0  50.0  1.020  4.0  0.0  normal    normal  notpresent
2      2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent
3      3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present
4      4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent
..   ...   ...   ...    ...  ...  ...     ...       ...         ...
395  395  55.0  80.0  1.020  0.0  0.0  normal    normal  notpresent
396  396  42.0  70.0  1.025  0.0  0.0  normal    normal  notpresent
397  397  12.0  80.0  1.020  0.0  0.0  normal    normal  notpresent
398  398  17.0  60.0  1.025  0.0  0.0  normal    normal  notpresent
399  399  58.0  80.0  1.025  0.0  0.0  normal    normal  notpresent

             ba  ...         sod       pot  hemo  htn   dm  cad appet   pe  \
0    notpresent  ...  137.528754  4.627244  15.4  yes  yes   no  good   no
1    notpresent  ...  137.528754  4.627244  11.3   no   no   no  good   no
2    notpresent  ...  137.528754  4.627244   9.6   no  yes   no  poor   no
3    notpresent  ...  111.000000  2.500000  11.2  yes   no   no  poor  yes
4    notpresent  ...  137.528754  4.627244  11.6   no   no   no  good   no
..          ...  ...         ...       ...   ...  ...  ...  ...   ...  ...
395  notpresent  ...  150.000000  4.900000  15.7   no   no   no  good   no
396  notpresent  ...  141.000000  3.500000  16.5   no   no   no  good   no
397  notpresent  ...  137.000000  4.400000  15.8   no   no   no  good   no
398  notpresent  ...  135.000000  4.900000  14.2   no   no   no  good   no
399  notpresent  ...  141.000000  3.500000  15.8   no   no   no  good   no

     ane classification
0     no            ckd
1     no            ckd
2    yes            ckd
3    yes            ckd
4     no            ckd
..   ...            ...
395   no         notckd
396   no         notckd
397   no         notckd
398   no         notckd
399   no         notckd

[400 rows x 23 columns]

In [23]:
dataset.isnull().sum()

id                0
age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hemo              0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64